refreshVersionsMigrate:
	./gradlew refreshVersionsMigrate --mode=VersionsPropertiesOnly

runServer:
	./gradlew :server:run

runDesktop:
	./gradlew :desktop:run

.PHONY: refreshVersionsMigrate runServer runDesktop
