refreshVersionsMigrate:
	./gradlew refreshVersionsMigrate --mode=VersionsPropertiesOnly

runServer:
	./gradlew :server:run

runDesktop:
	./gradlew :desktop:run

win-refreshVersionsMigrate:
    ./gradlew refreshVersionsMigrate --mode=VersionsPropertiesOnly

win-runServer:
    ./gradlew :server:run

win-runDesktop:
    ./gradlew :desktop:run

.PHONY: refreshVersionsMigrate runServer runDesktop win-refreshVersionsMigrate win-runServer win-runDesktop
