refreshVersionsMigrate:
	./gradlew refreshVersionsMigrate --mode=VersionsPropertiesOnly

runServer:
	./gradlew :server:run

runDesktop:
	./gradlew :desktop:run

win-refreshVersionsMigrate:
	./gradlew refreshVersionsMigrate --mode=VersionsPropertiesOnly

win-runServer:
	gradlew.bat :server:run

win-runDesktop:
	gradlew.bat :desktop:run

.PHONY: refreshVersionsMigrate runServer runDesktop win-refreshVersionsMigrate win-runServer win-runDesktop
